### ISSUE TITLE
v2 Lit feedback

### ISSUE THREAD

**Issue by balloob** [esphome/esphome-webserver#1]
Was browsing the source of v2. Here is some feedback based on the practices that we adopted for the [ESPHome dashboard repository](https://github.com/esphome/dashboard/).

`@property` decorator is meant for things set on the DOM element by others. For internal use, use `@state`.

The `@property` and `@state` decorators will trigger a re-render whenever their value changes. It's not necessary for properties that are not used directly in rendering or will never change (ie `source` in `<esp-app>`.

Initializing a class shouldn't have side-effects. So no constructors/instance variables that are instantiated. Instead, implement `firstUpdated(changedProps)` (don't forget to call super.firstUpdated(changedProps)`).

I would suggest to adopt `prettier` to format the code. Some lines have gotten very long and difficult to read.

Don't forget to call `super.updated(changedProps)` inside the `update` functions.

LitElement uses ShadowDOM which as CSS scoping. It's not necessary to use inline CSS.

**Comment by wilberforce** [comment]
> `@property` decorator is meant for things set on the DOM element by others. For internal use, use `@state`.
> 
> The `@property` and `@state` decorators will trigger a re-render whenever their value changes. It's not necessary for properties that are not used directly in rendering or will never change (ie `source` in `<esp-app>`.

https://github.com/esphome/esphome-webserver/blob/main/v2/esp-app.ts#L17-L22

So I should change the `@property` here to `@state` ?

> 
> Initializing a class shouldn't have side-effects. So no constructors/instance variables that are instantiated. Instead, implement `firstUpdated(changedProps)` (don't forget to call super.firstUpdated(changedProps)`).

https://github.com/esphome/esphome-webserver/blob/main/v2/esp-app.ts#L33-L55

So move this code into the `firstUpdated(changedProps)` method?

> 
> I would suggest to adopt `prettier` to format the code. Some lines have gotten very long and difficult to read.
> 

Is there a specific config for vscode that could be adopted here?


> Don't forget to call `super.updated(changedProps)` inside the `update` functions.
> 

Do you call super first or at the end of the update function?

> LitElement uses ShadowDOM which as CSS scoping. It's not necessary to use inline CSS.

Sorry, I'm not clear on where you are referring to here - please can you point me to an example?

**Comment by balloob** [comment]
> > `@property` decorator is meant for things set on the DOM element by others. For internal use, use `@state`.
> > The `@property` and `@state` decorators will trigger a re-render whenever their value changes. It's not necessary for properties that are not used directly in rendering or will never change (ie `source` in `<esp-app>`.
> 
> [`main`/v2/esp-app.ts#L17-L22](https://github.com/esphome/esphome-webserver/blob/main/v2/esp-app.ts?rgh-link-date=2021-12-31T22%3A56%3A24Z#L17-L22)
> 
> So I should change the `@property` here to `@state` ?

Yes

> > Initializing a class shouldn't have side-effects. So no constructors/instance variables that are instantiated. Instead, implement `firstUpdated(changedProps)` (don't forget to call super.firstUpdated(changedProps)`).
> 
> [`main`/v2/esp-app.ts#L33-L55](https://github.com/esphome/esphome-webserver/blob/main/v2/esp-app.ts?rgh-link-date=2021-12-31T22%3A56%3A24Z#L33-L55)
> 
> So move this code into the `firstUpdated(changedProps)` method?

Yes. You might want to instantiate the EventSource already above class definition (or even inside index.html so it's started before JS is even loaded).


> > I would suggest to adopt `prettier` to format the code. Some lines have gotten very long and difficult to read.
> 
> Is there a specific config for vscode that could be adopted here?

We always stick to the defaults to avoid any discussion.


> > Don't forget to call `super.updated(changedProps)` inside the `update` functions.
> 
> Do you call super first or at the end of the update function?

Do it first unless you have a specific reason to do it last.


> > LitElement uses ShadowDOM which as CSS scoping. It's not necessary to use inline CSS.
> 
> Sorry, I'm not clear on where you are referring to here - please can you point me to an example?
> 
> Do you mean this sort of thing? [`main`/v2/esp-app.ts#L85](https://github.com/esphome/esphome-webserver/blob/main/v2/esp-app.ts?rgh-link-date=2021-12-31T22%3A56%3A24Z#L85) `<a href="https://esphome.io/web-api" style="height:4rem;float:left;color:inherit">`
> 
> The reason I did this was if the css was moved to the css section - it would need to have a class/id assigned and this would take up more space (thinking of if the source was served from flash and trying to minimise flash space)

Ah good point. Is this going to be embedded in flash or always served from domain?

**Comment by wilberforce** [comment]
@balloob 
I have addressed the points raised above with https://github.com/esphome/esphome-webserver/commit/ea273dbed09bf995a7d4f25d3f2a5d9f2e3fb6f1

> Ah good point. Is this going to be embedded in flash or always served from domain?

Ideally I think 3 options would be good.
a. Default:  Serve from the new https://oi.esphome.io/v2/www.js
b. Have an option to serve locally from your homeassistant instance - then no dependance on the internet
c. An option to serve from flash. in the same way as https://github.com/esphome/esphome/pull/2872 
The index.html can be rolled up to contain the JS and inlined and compressed a served standalone on the device

**Comment by balloob** [comment]
Ok in that case let's stick with inline Css.

**Comment by wilberforce** [comment]
I've moved the larger inline styles to a class or id, and simplified the switch selectors (as the shadow dom keeps it specific anyway)

16 bytes smaller now ;-)

https://github.com/esphome/esphome-webserver/commit/0bbf717542d4c9e87498ace186f79d9986ea6807

**Comment by balloob** [comment]
It's a pity that we limit what we add to the webserver UI because of the case that it could be embedded in flash.

It might be better to make 2 entry points. A "lite" one that could be embedded and one for which we can go all out (whatever that would be).

**Comment by wilberforce** [comment]
> It might be better to make 2 entry points. A "lite" one that could be embedded and one for which we can go all out (whatever that would be).

Honestly it's a handful of bytes - I have converted the remaining inline styles https://github.com/esphome/esphome-webserver/commit/fe4e14404114af6620a98d94ac913e5342bc9e56
