### ISSUE TITLE
Instance names are not showing. Only the states and the action

### ISSUE THREAD

**Issue by charithmadhuranga** [esphome/esphome-webserver#2]
I have compile this in development environment and connect to my esp.Names of the instance are not  showing. 
eg - relay1 ,sensor1

this issue is refering to the version 2 web server

**Comment by wilberforce** [comment]
> this issue is refering to the version 2 web server

So the names are defaulting to the ids?

I believe you are using the old V1 webserver backend and using the new JS files from this repository.

The PR has not been pulled into the main dev stream yet. You would need to compile against https://github.com/wilberforce/esphome/tree/webserver-v2 to get the correct backend server code

**Comment by charithmadhuranga** [comment]
yes.That's the problem now its working.

**Comment by wilberforce** [comment]
> yes.That's the problem now its working.

Nice... gettting closer to this getting into the main branch...
