### ISSUE TITLE
Slider for Number Component unusable

### ISSUE THREAD

**Issue by jov58** [esphome/esphome-webserver#23]
Hi,

In version 1 number components had an input field, in version 2 this is replaced by a slider. Now, when columns `Name` and/or `State` are wide there is not enough room for the slider. This results in a slider which can not be operated or jumps to the `min` value.

Is there a way to force a number component to be represented by an input field? I think not, so I would like to propose to add an option for that in `web_server:` and/or `number:` component.

**Comment by jesserockz** [comment]
Indeed this needs to be possible. The YAML configuration contains `mode: auto/box/slider` which needs to be sent to the frontend and taken into account when displaying the control side.

**Comment by jesserockz** [comment]
Ignore my previous comment, it is already configured to do this. By default, `mode` will be set to `auto` and the frontend will always show a slider. If you set it to `box` in your yaml, you will get an input box

**Comment by jov58** [comment]
Well, how one (read: _me_) can overlook something completely, it's just there in the documentation. Feel a bit silly now.

Thanks!
