### ISSUE TITLE
Github Workflows

### ISSUE THREAD

**Issue by RoboMagus** [esphome/esphome-webserver#26]
In PR #25 the `make_header.sh` script fails with `xxd: command not found`.

Trying to look into this I could not find any record on how the Netlify deployments are triggered.
- How are the current PR checks implemented?
- Could these please be transitioned to GH Workflows, such that workflow improvements can be traced and contributed to as well?

For one, I'd like to propose the change that if the script fails, the check should not pass succesfully.

**Comment by jesserockz** [comment]
netlify is triggered via github webhooks whenever there is a new commit in `main`. It is configured to run `npm run build` and then host the contents from `_static` after that is done.
