### ISSUE TITLE
climate slider may have 0 size

### ISSUE THREAD

**Issue by tomaszduda23** [esphome/esphome-webserver#31]
If previous column is very large climate slider can have 0 size which allows to set only minimum size.

**Comment by tomaszduda23** [comment]
![IMG-20230214-WA0000](https://user-images.githubusercontent.com/35012788/219873627-9f00f9c3-27a7-4404-92f8-c68a2227badb.jpg)

**Comment by RFDarter** [comment]
@tomaszduda23 any workarround on this yet?
