### ISSUE TITLE
Slider width is 0 on mobile

### ISSUE THREAD

**Issue by RojRa** [esphome/esphome-webserver#32]
The issue is related to #31

### The slider element on Mobile has width of 0, making it unusable

![image](https://user-images.githubusercontent.com/128071417/225687398-cb43e4b0-d1c1-4d9c-8501-2bae6973877b.png)

### Desktop looks good though:

![desktop_Chrome](https://user-images.githubusercontent.com/128071417/225685333-2987f1e2-c077-4a62-9b68-c3746a9ae269.PNG)

### Code snippet of the slider from my test:

`number:`
`  - platform: template`
`    name: Slider`
`    optimistic: true`
`    min_value: 10`
`    max_value: 60`
`    step: 10`
`

**Comment by RFDarter** [comment]
@RojRa  have you found any workaround yet?
