### ISSUE TITLE
Template number not changeable in webserver

### ISSUE THREAD

**Issue by Gafielt** [esphome/esphome-webserver#35]
The action row is missing for template number components. Not sure if this is the same for text or other stuff. I am pretty sure this has something to do with #29. Also mentioned in https://github.com/esphome/issues/issues/4602

PS: sorry for no screenshots or example code. I'm typing this on the go as I recognized the error. Will add proof later today or tomorrow if needed.

**Comment by wilfredktlr** [comment]
I just encountered the [same problem](https://github.com/esphome/issues/issues/4606) with a button control.

**Comment by WorlockM** [comment]
Thanks for linkin your issue to mine. Seems to be the problem yes. What I don't understand about it is that I didn't update anything?

**Comment by wilfredktlr** [comment]
This is because the problem is in the publicly hosted JavaScript https://oi.esphome.io/v2/www.js and it has nothing to do with the ESP device itself. Everyone who uses this file has the same problem no matter the ESPHome version they have installed on their device.

**Comment by WorlockM** [comment]
Thanks for explaining :)

**Comment by Gafielt** [comment]
Hopefully this will get fixed soon. Is there a way to get it working by reversing the JavaScript file and prevent breaking changes without updating?

**Comment by trip5** [comment]
Looks like the JS file can be hosted by the device itself: [doc](https://esphome.io/components/web_server.html)
But where to get the old javascript file?  I've tried editing out the offending change but the raw javascript is dense and I wasn't successful.

```
web_server:
  port: 80
  ota: true
  include_internal: true
  js_include: "./www/v2_www.js"
```

**Comment by Gafielt** [comment]
> Looks like the JS file can be hosted by the device itself: [doc](https://esphome.io/components/web_server.html)
> But where to get the old javascript file?
> ```
> web_server:
>   port: 80
>   ota: true
>   include_internal: true
>   js_include: "./www/v2_www.js"
> ```
> So I edited the current public JS and removed the offending changes.
> https://gist.github.com/trip5/12f2130f8cc326a91a800103a36ed0d1

Thanks for your effort, but unfortunately it did not work in my case. I'm not sure if the js file was accepted or not, but it did not work even with a new build with deletion of .esphone beforehand. The only way I got it to work currently is to setup a dummy switch.

**Comment by trip5** [comment]
Which means the local JS is meant as a fallback if the device can't reach the Internet but if the url is blank then of course it fails.  I probably knew that but neglected it.  Added a note to the gist if anyone else needs it.
