### ISSUE TITLE
The width of input text (Template Text) is short.

### ISSUE THREAD

**Issue by vespadj** [esphome/esphome-webserver#47]
The width of `<input>` for a Template Text is short.
My suggest:
Add attrubute:
`size="maxLength value"` (from 1 to 255)

**Comment by vespadj** [comment]
```css
input[type="text"] {
          width: calc(100% - 8rem);
```
should be
```css
          width: calc(100% - 0.5rem);
```
Attribute `size` is not necessary.

**Comment by RFDarter** [comment]
The Webserver is basicly unusable on a smartphone.
The silder of a number component has no width, the same with the text.

@vespadj do you have any workaround to make it useable?

**Comment by vespadj** [comment]
> @vespadj do you have any workaround to make it useable?

@RFDarter, no I'm sorry. You need to use home assistant, I suppose, or write your own js / css.
Width and Margins could be revised.
