### ISSUE TITLE
v3 Does not show icons if they are defined through the device class

### ISSUE THREAD

**Issue by andrewjswan** [esphome/esphome-webserver#70]
Does not show icons if they are defined through the device class, only if specify them separately in the configuration.

**Comment by andrewjswan** [comment]
```
platform: wifi_signal
name: ${name} WiFi Signal
update_interval: ${update_interval}

platform: status
name: ${name} Status
device_class: connectivity
```

But no Icon in Web

**Comment by ssieb** [comment]
oh, I misunderstood what you meant by the device class.  That's only going to affect maybe HA.  If you want an icon, then define it.

**Comment by andrewjswan** [comment]
device class means an icon and a unit of measurement.  Is it possible that ESPHome doesn’t have this information?

**Comment by andrewjswan** [comment]
> It doesn't. Those parameters are passed to HA.

I thought that at the time of assembly, a unit of measurement and an icon are automatically registered based on the device class, because in WEB the units of measurement are visible, but they are also not in the config.

**Comment by ssieb** [comment]
Most sensors have the icon, units, and device class pre-configured for you.

**Comment by andrewjswan** [comment]
Then all this should be displayed on the WEB

**Comment by jesserockz** [comment]
@andrewjswan Both the `status` binary sensor and the `wifi_signal` sensor do not have icons defined in ESPHome as HA automatically can assign icons based on the device class.

**Comment by andrewjswan** [comment]
Bad news ... :(

**Comment by RFDarter** [comment]
> Bad news ... :(

Actually good news since it seems like there is no issue on the webserver side.
