### ISSUE TITLE
v3 Allow controls to use more space

### ISSUE THREAD

**Issue by pzich** [esphome/esphome-webserver#72]
Right now it seems like the controls column is fixed at 500px, and that the entity names and controls split this width 50%, minus some margin. This means that the controls only get 204px of space to fit, even if the name is short and the window is thousands of pixels wide.

![Fixed 500px](https://github.com/esphome/esphome-webserver/assets/706138/35c499aa-d663-452c-9823-f8dbf54a149e)
![204px Name](https://github.com/esphome/esphome-webserver/assets/706138/c0e78525-2767-4d9b-ae19-790e1e4f1c4d)
![204px Control](https://github.com/esphome/esphome-webserver/assets/706138/921f0258-893a-4979-9730-a2b0e0636384)

Personally, it seems like the controls should be able to occupy more space, at least if the name is short (or maybe always?)

I'm no flex box expert, but it seems like changing the flex-basis of the second column (name) to `auto`, and adding a `flex-grow: 1` to the entity control element gives this a lot more room to work with.

![Auto width](https://github.com/esphome/esphome-webserver/assets/706138/101771f0-b031-4306-ad72-8df133bc9196)

Does this seem like a reasonable change? Or maybe the controls can even be full width, and have the name moved to the top left corner of the control?

**Comment by RFDarter** [comment]
I am not on the PC atm, so i cant test it. What happens to the control if the name is realy long?
In your example it is not long enoth to Intefere with the switch. But happens to a slider?  Is there a min width so it stays usable?
I like the idea of the control usint the whole space and the name is shifted. Could you make a prove if concept of that so we could get a feel for what it could look like?

**Comment by RFDarter** [comment]
I would like to try it out and see if it will not get to chaotic if the names are all diffeent in lenght.
Would you mind sharing your work?

**Comment by RFDarter** [comment]
> Should there still be a way to see the full name? Maybe by hovering or tapping it?

I think it would make send to somehow be able to see the full name

**Comment by pzich** [comment]
I took a stab at getting the basics to work in jsfiddle, but still need to test actually integrating it
https://jsfiddle.net/d24rcfyu/
